Snaacky/thewiki

docs/hidden/chiya-mod-info.md
docs/hidden/faq-creating-your-own-site.md
docs/hidden/faq-general.md
docs/hidden/faq-streaming.md
docs/hidden/faq-torrent.md
docs/hidden/faq-vpn.md
docs/hidden/faq.md
docs/hidden/index.yml
docs/hidden/organization.md
docs/hidden/quick-start.md
docs/hidden/ripping.md
docs/hidden/rules.md
docs/hidden/seadex-tutorial.md
docs/hidden/sponsored-listing.md
docs/hidden/terminology.md
docs/hidden/trials.md
docs/hidden/unblock.md
docs/hidden/vips.md

These should be all of the hidden files unless I missed some.

Add unpublished/hidden files

---

docs/advanced/index.yml
docs/faq/faq-general.md
docs/faq/faq-streaming.md
docs/faq/faq-torrent.md
docs/faq/faq-vpn.md
docs/faq/index.yml
docs/tutorials/index.yml

Includes:
- General FAQ
- Torrent FAQ
- Streaming FAQ
- VPN FAQ

Add FAQ as a new category

---

docs/faq/faq-streaming.md
docs/faq/faq-torrent.md
docs/guides/quality.md
docs/tutorials/comparison.md
docs/tutorials/mpv.md
docs/tutorials/oped.md
docs/tutorials/rss.md

fixed any quick and easy formatting errors that I could find

Small formatting fixes

---

docs/guides/torrenting.md

torrenting.md guide page was full of broken formatting carried over from wiki.js. This should hopefully make it better.

reduced the infobox spam

---

docs/advanced/index.yml
docs/getting-started/index.yml
docs/resources/index.yml
docs/sourcing/index.yml

Add icons to sidebar categories

---

docs/index.md

add icon and img

---

docs/tutorials/mpv.md

Additional notes, warnings, and image where they made sense. Also added a description for page metadata. Minor formatting improvements

Improvements for MPV tutorial

---

docs/index.md

an attempt at improving the homepage

homepage overhaul

---

docs/getting-started/anime.md

no idea how gif embeds work so let's see

added embed and description to anime.md

---

docs/tutorials/torrent.md

- Explained things a bit more
- Added [torf-cli](https://github.com/rndusr/torf-cli)
- improved formatting using retype components

Added torf-cli, explained things a bit better, and improved formatting

---

docs/sourcing/streaming.md

Updated the streaming guide to remove obsolete websites and add relevant replacements.

Updated streaming guide.

---

docs/sourcing/streaming.md

Changed mention of tenshi to Marin, and added another comparison.

Fixed typo and added another comp

---

docs/tutorials/plex.md

- updated some information regarding lack of plex pass requirements
- [hopefully] fixed open graph title
- updated changes related to libmpv naming which changed in 2023

fix: plex mod changes, details, OG

---

docs/getting-started/anime.md
docs/getting-started/hentai.md
docs/getting-started/literature.md
docs/getting-started/music.md
docs/getting-started/torrenting.md
docs/tutorials/deluge.md
docs/tutorials/qbittorrent.md
docs/tutorials/transmission.md
docs/tutorials/vpn-binding.md

- added a "getting started with torrenting" guide
- added qbittorrent tutorial
- added transmission tutorial
- added deluge tutorial
- added vpn-binding tutorial

feat: new torrenting guide, torrent client and vpn binding tutorials

---

docs/resources/tutorials.md
docs/tutorials/visualnovels.md

This PR adds a Visual Novel asset extraction guide to the wiki.

feat: Visual Novel asset extraction guide

---

docs/tutorials/mpv.md

Closes https://github.com/Snaacky/thewiki/issues/52
Went with expanding the same page over a new one. Although it's still up for change.

feat: add collection of MPV configs

---

docs/getting-started/hentai.md
docs/getting-started/music.md

It's a start, but I added some potentially useful info. More to come soon. Also, I updated my info on hentai.md because I changed my username back.

feat: rewrite music.md

---

docs/tutorials/comparison.md

https://myheroacademia.fandom.com/wiki/Kai_Chisaki

feat: comparison overhaul (MHA reference)

---

docs/resources/glossary.md

add `Neutral leech` to glossary

add `Neutral leech` to glossary

---

docs/tutorials/torrent.md

Save thanosloads of vertical bloat by using TABS
Closes https://github.com/Snaacky/thewiki/issues/106

fix: make prettier

---

.gitattributes

This reverts commit 3ef8cbfa20d9aa3a5c6d54ee2ad5828cba0b786c.

Revert "fix: git lfs (#112)"

---

docs/guides/torrenting.md

'devices' wasn't spelt right, and 'need' wasn't in the right conjugation

fix: minor fixes

---

docs/guides/torrenting.md

Revert "fix: minor fixes"

---

docs/tutorials/comparison.md

fix: go back to `/static`

---

docs/advanced/release-standards.md
docs/advanced/typesetting.md

Catching up on backlog, said I'd add this over 3 months ago, but didn't have time x)
I don't get this order thing, idk if it's global, or per block
guide itself is mid and a bit outdated, but it's better than none

feat: typesetting

---

docs/guides/quality.md

Closes https://github.com/Snaacky/thewiki/issues/124

fix: clarify fps in quality guide

---

.github/workflows/links.yml
docs/getting-started/literature.md

https://github.com/lycheeverse/lychee-action
This will help us catch any broken links in the future

feat: add a link checker workflow

---

docs/tutorials/mpv.md

mpv received some major updates recently, rendering the guide outdated.
- https://github.com/mpv-player/mpv/commit/703f1588803eaa428e09c0e5547b26c0fff476a7
- https://github.com/mpv-player/mpv/commit/981a9372ff0034178a986f8bc1ec1ad6b973bb6c

fix: update mpv guide due to recent mpv changes

---

docs/tutorials/mpv.md

Revert "fix: update portable mpv builds"

---

docs/tutorials/comparison.md

Updated the comp script so that it uses better tonemapping defaults

fix: better tonemapping for the comp script

---

docs/getting-started/hentai.md

Added Koshoku to the hentai guide

feat: add koshoku to `docs/getting-started/hentai.md`

---

.github/workflows/links.yml
docs/getting-started/hentai.md
docs/getting-started/music.md

Closes https://github.com/Snaacky/thewiki/issues/173

chore: remove dead links

---

docs/getting-started/hentai.md
docs/getting-started/music.md

- fix: updated dead link in music.md

feat: add anchira to `docs\getting-started\hentai.md`

---

docs/tutorials/comparison.md

hostile takeover or schizophrenia, I have no idea

fix(comparison): update vspreview's github link

---

docs/getting-started/music.md

original link is now dead for whatever reason
Closes https://github.com/Snaacky/thewiki/issues/185

fix(music): update sox's link

---

docs/getting-started/music.md

https://sox.sourceforge.net/sox.html is dead

fix(music): replace sox's docs page with webarchive mirror

---

docs/sourcing/private-trackers.md

fix(private-trackers): typo

---

docs/tutorials/mpv.md

https://github.com/mpv-player/mpv/commit/1370ecfc1b9b477aecc552355a0ac5f8555e51ae
https://github.com/mpv-player/mpv/commit/b626f3ba8367d88e3526efa49961f91af4a6620c

fix(mpv): replace deprecated options

---

docs/getting-started/hentai.md
docs/getting-started/music.md

Updated page information to reflect current username

fix: update dead author link in hentai.md & music.md

---

docs/static/tutorials/mpv/portable_config/mpv.conf

feat(mpv): inline function for autoprofile

---

docs/getting-started/literature.md

feat(literature): add ComicK

---

docs/advanced/muxing.md

This is an ISO household, must have been low sleep that caused this

fix: use ISO 8601 date

---

docs/guides/htpc.md

add control section, linux section.

fix(htpc): update

---

docs/static/tutorials/mpv/portable_config/input.conf
docs/static/tutorials/mpv/portable_config/mpv.conf
docs/tutorials/mpv.md

closes https://github.com/Snaacky/thewiki/issues/266

fix(mpv): update mpv deband

---

docs/tutorials/comparison.md

feat(comparison): update stuff for python 3.12

---

docs/getting-started/literature.md

Closes https://github.com/Snaacky/thewiki/issues/272
Closes https://github.com/Snaacky/thewiki/issues/273

fix(literature): remove dead kavita link

---

.github/workflows/links.yml
docs/getting-started/hentai.md
docs/getting-started/music.md

Closes https://github.com/Snaacky/thewiki/issues/291

fix: remove dead link

---

docs/getting-started/hentai.md

Updated dead links, added Panda Backup, and updated site descriptions.

fix(hentai): remove dead links

---

docs/getting-started/hentai.md

Updated Anchira section with new link

fix(hentai): update anichira

---

docs/sourcing/streaming.md

Closes https://github.com/Snaacky/thewiki/issues/311

fix: remove dead links

---

docs/tutorials/dvdremux.md

fix(dvdremux): add PAL table

---

docs/getting-started/torrenting.md

Closes https://github.com/Snaacky/thewiki/issues/328
Closes https://github.com/Snaacky/thewiki/issues/327
Closes https://github.com/Snaacky/thewiki/issues/322
Closes https://github.com/Snaacky/thewiki/issues/319
Closes https://github.com/Snaacky/thewiki/issues/318

fix(torrenting): update proton link

---

docs/static/tutorials/mpv/portable_config/mpv.conf

Ref: https://github.com/mpv-player/mpv/pull/14731
Ref: https://discord.com/channels/771790175591333909/884837742868070450/1284647564670668873 (seadex)

fix(mpv): replace outdated setting

---

docs/getting-started/literature.md

- added touch lua script as an alternative to GestureSign
- replaced the iOS reader comp with a more comprehensive one courtesy of succ_

fix(literature): update mpv touch usage instructions

---

docs/tutorials/comparison.md

Remove all the old/unnecessary stuff, update everything for the current VSPreview version which has had significant changes

Update for latest VSPreview

---

docs/getting-started/literature.md

Add Komelia.md

---

docs/tutorials/mpv.md

ref: https://discord.com/channels/771790175591333909/884837742868070450/1333397638149574720 (seadex)

fix(mpv): added sub-margin-y=40

---

docs/advanced/fansubbing.md

https://discord.com/channels/974468300304171038/1125821479636979773/1343030538604249118
would prefer lowercase g please
yes it's a nitpick but it's my name, i'd prefer it was spelt properly (always lowercase for internet stuff)

fix(fansubbing): lowercase g
