docs/faq/faq-general.md, docs/faq/faq-streaming.md, docs/faq/faq-torrent.md, docs/getting-started/anime.md, docs/guides/torrenting.md, docs/hidden/faq-general.md, docs/hidden/faq.md, docs/hidden/quick-start.md, docs/sourcing/streaming.md
Wiki.js had `/en/` indicating the locale in the links and that carried over to retype which ended up breaking several links. For example:
```diff
-[Sourcing - Quality](/en/guides/sourcing#quality)
+[Sourcing - Quality](/guides/sourcing#quality)
```
=> removing /en/ from all the links

docs/advanced/muxing.md, docs/advanced/release-standards.md, docs/getting-started/literature.md, docs/hidden/seadex-tutorial.md, docs/hidden/sponsored-listing.md, docs/tutorials/comparison.md, docs/tutorials/mpv.md, docs/tutorials/propolis.md, docs/tutorials/sonarr.md
Imgur is [updating their ToS](https://help.imgur.com/hc/en-us/articles/14415587638029-Imgur-Terms-of-Service-Update-April-19-2023-) to remove all existing uploads that aren't tied to an account, which is pretty much every imgur link in this repo.
=> fix: replace imgur links with github links

docs/getting-started/music.md
Added a section to music.md that recommends SoX for spectrogram generation along with a helpful script to do so.
=> feat: add section on spectral analysis with SoX

docs/getting-started/music.md
Accidentally left an open part of an unused hyperlink :sweat_smile:
=> fix: typo in music.md

docs/sourcing/streaming.md
Added a new scraper to show in the examples section of streaming.md and a quality comparison using "Oshi no Ko," comparing a few streaming sites (9anime, Gogoanime, Marin, Zoro) and torrents.
Other changes include:
- Omitting inactive/obsolete sites from examples. These scrapers (11anime, 5anime, and Animeflix) no longer exist.
- Adjusting capitalization for consistency. Minor changes (i.e. "zoro" to "Zoro").
- Added a reference to Marin's former site "tenshi."
- The quality comparison using "Vinland Saga S2" does not include 9anime or Zoro due to mismatched frames. Removed as they do not exist in the slow.pics comparison. Gogo was added since it exists.
=> feat: add new scraper site and quality comparison for streaming.md

docs/getting-started/anime.md, docs/sourcing/streaming.md
Redesign for sourcing/streaming.md and getting-started/anime.md to simplify information and utilize Retype's components for a more organized look.
Majority of the documentation was rewritten to make it easier to understand for the user, while also maintaining a similar or better level of information.
Some other changes include:
- Reducing information that isn't necessary in anime.md, directing users to the main page if they wish to learn more.
- Fixing links to pages that have been moved or removed.
- Recommending the user a reliable content/ad blocker in streaming.md and anime.md.
- Warnings (i.e. copyright notices through torrenting, fake streaming sites).
- Amending grammatical and formatting errors.
[These changes can be previewed live here.](https://ricky8k.github.io/thewiki/)
=> feat: redesign sourcing/streaming.md and getting-started/anime.md

docs/sourcing/streaming.md
Streaming site [Zoro](https://zoro.to) recently rebranded to [AniWatch](https://aniwatch.to) (not to be confused with [_Aniwatch_](https://aniwatch.me)). This PR removes their old domain and replaces it with the new destination. Added a note mentioning their former site (like Marin's old site).
Seeing as it conflicts with _Aniwatch_, it might be best to add a note somewhere as well.
=> fix: rebrand streaming site Zoro to AniWatch

docs/getting-started/anime.md, docs/guides/playback.md, docs/index.md, docs/tutorials/mpv.md
Redesign for guides/playback.md to simplify information and utilize Retype's components for a more organized look. Similar to the changes introduced in PR https://github.com/Snaacky/thewiki/pull/78.
Some changes include:
- Fixing grammatical errors and linking in index.md.
- Removing outdated information (i.e. most media servers can't play `.ass` subs)
- Improved scaling shader recommendations for mpv.
- Condensing/revising documentation (i.e. scaling, explaining judder, codecs).
[These changes can be previewed live here.](https://ricky8k.github.io/thewiki/)
=> feat: redesign guides/playback.md

docs/sourcing/streaming.md
Streaming site [AnimeDao](https://animedao.to) recently shut down. This PR removes reference of their site.
Other changes include:
- Using Retype tabs instead of panels to reduce vertical space
- Amending markdown lint/formatting errors
=> fix: remove AnimeDao in sourcing/streaming.md

docs/guides/quality.md, docs/sourcing/streaming.md
Streaming site [9anime](https://9anime.to) recently rebranded to [AniWave](https://aniwave.to). This PR removes their old domain and replaces it with the new destination. Added a note mentioning their former site, similar to AniWatch (https://github.com/Snaacky/thewiki/pull/81) and Marin.
=> fix: rebrand streaming site 9anime to AniWave

docs/guides/quality.md, docs/sourcing/streaming.md
Added a new quality comparison using "[Masamune-kun no Revenge R](https://slow.pics/c/rj3QjRMA)," comparing a variety of sources including an encode, official, minis, and streaming sites.
Other minor changes include:
- Replacing "Web" to "WEB" for proper terminology
- Changing SubsPlease to be an "Official" source rather than an "Encode," which was previously incorrect
=> feat: add new quality comparison

docs/guides/quality.md, docs/sourcing/streaming.md
The growing number of comparisons does not fit well with the current system of bullet lists. This PR proposes a unified table design for the quality comparisons on guides/quality.md and sourcing/streaming.md moving forward.
Other changes include:
- Adding the new [quality comparison from Snackbox](https://slow.pics/c/Fnkp1NrA) comparing a raw and multiple encodes/minis
- Adding information about mini encodes in Types of Releases. I believed that it was too short and had lacked some useful info, downplaying minis more than they should've been
- Highlighting re-encodes in red for comparisons, making it easy to understand given the new approach
=> feat: redesign quality comparisons

docs/tutorials/mpv.md
Redesign for tutorials/mpv.md to simplify information and utilize Retype's components for a more organized look.
Some changes include:
- Using a GIF for Windows, demonstrating installation
- Recommending application forks which use mpv (e.g. [ImPlay](https://github.com/tsl0922/ImPlay))
- Updating the [portable builds of mpv](https://github.com/Snaacky/thewiki/releases/tag/mpv-v20230806)
- Using a table instead of a bullet list for explaining the Basic Config
- Fixing grammatical errors
I need some feedback on the Installation section of the guide, as I'm unsure on how I should format it. For instance, I omitted the installation with Scoop section as I believed it may not be necessary for most users, but I would like to hear what you think.
[These changes can be previewed live …
=> feat: redesign tutorials/mpv.md

docs/hidden/guide-torrenting-old.md
Torrenting guide was superseded by https://github.com/Snaacky/thewiki/pull/114
Putting this in hidden instead of deleting it merely for archiving
=> chore: archive the old torrenting guide

docs/tutorials/mpv.md, docs/tutorials/qbittorrent.md
Embeds nested in tabs do not load when their tab is reselected. Switching to panels for now until the issue is hopefully resolved by Retype.
Reference: https://github.com/retypeapp/retype/issues/613
=> fix: use panels instead of tabs

docs/tutorials/comparison.md
linked correct version and removed 'how to use' section since it's almost word for word in my repo's readme. if left in it could become outdated as i update the script, and could be a pain to maintain.
=> fix: baws comp script

docs/tutorials/mpv.md
Although I like the idea of us providing the pre configured mpv builds, it's practically impossible to keep them up to date.
=> fix(mpv): replace prebuilds with scoop

docs/getting-started/anime.md, docs/guides/playback.md, docs/guides/quality.md, docs/tutorials/comparison.md, docs/tutorials/mpv.md
This commit includes various cleanup fixes and consistency changes, some which rectify issues from previous commits.
Some changes include:
- `getting-started/anime`: Slightly changed terminology and updated playback table to reflect `guides/playback`
- `guides/quality`: Used table for lossy audio bitrate baselines and added surround conversions
- `tutorials/mpv`: Simplified dithering intro
=> chore: design consistency and cleanup

docs/tutorials/dvdremux.md
Matroska’s display dimensions don’t have to be given in absolute pixels. They can be an exact fraction, which allows the file to be displayed more accurately when combined with upscaling and/or cropping. For maximum compliance with the Matroska spec, set `display-unit` to 3, which means “display aspect ratio”; the default is 0, meaning “pixels”.
cc @wiwaz
Extra notes:
* In some situations, rounding might be more convenient (e. g. if the remux is gonna be subtitled in ASS with pixel-perfect typesetting; although that will break in the presence of container crop regardless of the aspect ratio).
* When `width` and `height` are both exact integers, the display dimensions could be set in pixels and be exact, too. I would do this, personally (out of an overabundance of caution regarding media …
=> dvdremux.md: set exact aspect ratio

docs/advanced/muxing.md
The old link didn't lead anywhere because it points at a header that no longer exists.
=> Fix "Practical Example" link in muxing

docs/sourcing/streaming.md
Removed links to gogoanime/anitaku from streaming because the site no longer exists.
=> fix: removed mentions of gogoanime/anitaku

docs/advanced/muxing.md
After some testing, it seems mpv no longer automatically selects a track if there's no `default=yes` tracks available (as of this PR https://github.com/mpv-player/mpv/pull/8865 specifically, it looks like). This prompted me to update that section of the wiki, and evidently, it got out of hand.
The additional explanations on track selection are modified examples from the [Matroska spec](https://www.matroska.org/technical/notes.html#default-track-selection) to better reflect more typical anime releases (with some uncommon additions to better explain specific interactions). I also made it a bit more a point to forefront the "Original language" flag, in part because I'd like to see these more widely adopted by muxers and so that hopefully other players (such as mpv) may add a parameter to …
=> Muxing: Update track selection and tagging sections
